productpage:
  namespace: student16-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
  image: ghcr.io/chayanpx/bookinfo-productpage
  tag: prd
ingress:
  host: itkmitl.bookinfo.opsta.net
  path: "/student16/productpage(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  REVIEWS_HOSTNAME: http://bookinfo-prd-reviews:8082
  RATINGS_HOSTNAME: http://bookinfo-prd-ratings:8080
  DETAILS_HOSTNAME: http://bookinfo-prd-details:8081
